### PR TITLE
Run def-conversions only once

### LINKED ISSUE #26: Unable to load byte-streams ns more than once
Here's an example repl session (from a fresh clone of byte-streams, with no other code):

```text
$ lein repl
nREPL server started on port 46803 on host 127.0.0.1 - nrepl://127.0.0.1:46803
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.8.0
OpenJDK 64-Bit Server VM 1.8.0_121-b13
Reflection warning, /home/jeaye/projects/lets-bet/byte-streams/target/9ebf76f7ebb52177860c3ac205bfc4727d674f41-init.clj:1:1589 - reference to field ns can't be resolved.
Reflection warning, /home/jeaye/projects/lets-bet/byte-streams/target/9ebf76f7ebb52177860c3ac205bfc4727d674f41-init.clj:1:3847 - reference to field name can't be resolved.
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (use 'byte-streams :reload-all)
WARNING: vector-of already refers to: #'clojure.core/vector-of in namespace: user, being replaced by: #'byte-streams/vector-of
nil
user=> (use 'byte-streams :reload-all)

user=>      java.lang.IllegalArgumentException: No implementation of method: :assoc-conversion of protocol: #'byte-streams.graph/IConversionGraph found for class: byte_streams.graph.ConversionGraph
clojure.lang.Compiler$CompilerException: java.lang.IllegalArgumentException: No implementation of method: :assoc-conversion of protocol: #'byte-streams.graph/IConversionGraph found for class: byte_streams.graph.ConversionGraph, compiling:(byte_streams.clj:334:1)

user=> *e
#error {
 :cause "No implementation of method: :assoc-conversion of protocol: #'byte-streams.graph/IConversionGraph found for class: byte_streams.graph.ConversionGraph"
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message "java.lang.IllegalArgumentException: No implementation of method: :assoc-conversion of protocol: #'byte-streams.graph/IConversionGraph found for class: byte_streams.graph.ConversionGraph, compiling:(byte_streams.clj:334:1)"
   :at [clojure.lang.Compiler load "Compiler.java" 7391]}
  {:type java.lang.IllegalArgumentException
   :message "No implementation of method: :assoc-conversion of protocol: #'byte-streams.graph/IConversionGraph found for class: byte_streams.graph.ConversionGraph"
   :at [clojure.core$_cache_protocol_fn invokeStatic "core_deftype.clj" 568]}]
 :trace
 [[clojure.core$_cache_protocol_fn invokeStatic "core_deftype.clj" 568]
  [clojure.core$_cache_protocol_fn invoke "core_deftype.clj" 560]
  [byte_streams.graph$eval21215$fn__21240$G__21196__21253 invoke "graph.clj" 91]
  [clojure.lang.AFn applyToHelper "AFn.java" 171]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.Atom swap "Atom.java" 79]
  [clojure.core$swap_BANG_ invokeStatic "core.clj" 2263]
  [clojure.core$swap_BANG_ doInvoke "core.clj" 2253]
  [clojure.lang.RestFn invoke "RestFn.java" 529]
  [byte_streams$eval22066 invokeStatic "byte_streams.clj" 336]
  [byte_streams$eval22066 invoke "byte_streams.clj" 336]
  [clojure.lang.Compiler eval "Compiler.java" 6927]
  [clojure.lang.Compiler load "Compiler.java" 7379]
  [clojure.lang.RT loadResourceScript "RT.java" 372]
  [clojure.lang.RT loadResourceScript "RT.java" 363]
  [clojure.lang.RT load "RT.java" 453]
  [clojure.lang.RT load "RT.java" 419]
  [clojure.core$load$fn__5677 invoke "core.clj" 5893]
  [clojure.core$load invokeStatic "core.clj" 5892]
  [clojure.core$load doInvoke "core.clj" 5876]
  [clojure.lang.RestFn invoke "RestFn.java" 408]
  [clojure.core$load_one invokeStatic "core.clj" 5697]
  [clojure.core$load_all$fn__5618$fn__5621 invoke "core.clj" 5713]
  [clojure.core$load_all$fn__5618 invoke "core.clj" 5713]
  [clojure.lang.AFn call "AFn.java" 18]
  [clojure.lang.LockingTransaction run "LockingTransaction.java" 273]
  [clojure.lang.LockingTransaction runInTransaction "LockingTransaction.java" 229]
  [clojure.core$load_all invokeStatic "core.clj" 5711]
  [clojure.core$load_all invoke "core.clj" 5705]
  [clojure.core$load_lib$fn__5626 invoke "core.clj" 5737]
  [clojure.core$load_lib invokeStatic "core.clj" 5736]
  [clojure.core$load_lib doInvoke "core.clj" 5717]
  [clojure.lang.RestFn applyTo "RestFn.java" 142]
  [clojure.core$apply invokeStatic "core.clj" 648]
  [clojure.core$load_libs invokeStatic "core.clj" 5774]
  [clojure.core$load_libs doInvoke "core.clj" 5758]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 650]
  [clojure.core$use invokeStatic "core.clj" 5860]
  [clojure.core$use doInvoke "core.clj" 5860]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [user$eval18373 invokeStatic "9ebf76f7ebb52177860c3ac205bfc4727d674f41-init.clj" 1]
  [user$eval18373 invoke "9ebf76f7ebb52177860c3ac205bfc4727d674f41-init.clj" 1]
  [clojure.lang.Compiler eval "Compiler.java" 6927]
  [clojure.lang.Compiler eval "Compiler.java" 6890]
  [clojure.core$eval invokeStatic "core.clj" 3105]
  [clojure.core$eval invoke "core.clj" 3101]
  [clojure.main$repl$read_eval_print__7408$fn__7411 invoke "main.clj" 240]
  [clojure.main$repl$read_eval_print__7408 invoke "main.clj" 240]
  [clojure.main$repl$fn__7417 invoke "main.clj" 258]
  [clojure.main$repl invokeStatic "main.clj" 258]
  [clojure.main$repl doInvoke "main.clj" 174]
  [clojure.lang.RestFn invoke "RestFn.java" 1523]
  [clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__941 invoke "interruptible_eval.clj" 87]
  [clojure.lang.AFn applyToHelper "AFn.java" 152]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 646]
  [clojure.core$with_bindings_STAR_ invokeStatic "core.clj" 1881]
  [clojure.core$with_bindings_STAR_ doInvoke "core.clj" 1881]
  [clojure.lang.RestFn invoke "RestFn.java" 425]
  [clojure.tools.nrepl.middleware.interruptible_eval$evaluate invokeStatic "interruptible_eval.clj" 85]
  [clojure.tools.nrepl.middleware.interruptible_eval$evaluate invoke "interruptible_eval.clj" 55]
  [clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__986$fn__989 invoke "interruptible_eval.clj" 222]
  [clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__981 invoke "interruptible_eval.clj" 190]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1142]
  [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 617]
  [java.lang.Thread run "Thread.java" 745]]}
```

This is breaking my development tooling, far down the dependency hole, but I've traced it back to byte-streams.

### PR DESCRIPTION
**Pull request by jeaye**
Fix #26 

Adding `?w=1` will rule out the whitespace differences and show just the couple of lines that changed. Here's a link: https://github.com/ztellman/byte-streams/pull/27/files?w=1

### CODE REVIEW

**Comment by jeaye** [comment]
Adding a regression test. Gimme a bit before merging, please.

**Comment by jeaye** [comment]
Ok, all set on my end.

**Comment by jeaye** [comment]
@ztellman Any chance of getting a release soon?

**Comment by ztellman** [comment]
Just cut `0.2.3-alpha1`, sorry for the delay.  Please feel free to follow up sooner in the future, this just completely slipped my mind.

**Comment by jeaye** [comment]
@ztellman Thank you. For how long are byte-streams releases typically in alpha? I'm wondering if I should hold off on the PRs to other libs until `0.2.3` is out.

**Comment by ztellman** [comment]
Which other libraries? The `:reload-all` workflow is not a typical one (for basically the reasons we ran into here), and it can be fixed by overwriting the dependencies in your project if you need it fixed.  If this is affecting lots of people, I'm happy to cut a new release, but usually I'd wait for a few other changes to accumulate.

**Comment by jeaye** [comment]
I have been waiting to update https://github.com/aprobus/jerks-whistling-tunes/ (some discussion [here](https://github.com/aprobus/jerks-whistling-tunes/pull/1)) to resolve this issue so that I can ultimately update https://github.com/jeaye/ring-gatekeeper (and, ideally, its upstream).

The `:reload-all` workflow is essential for any non-trivial, repl-driven server development; I don't see how else it would work.

**Comment by ztellman** [comment]
I just update single namespaces, and avoid anything which holds onto references to older implementations.  Perhaps I'm in the minority there, however.  I have no objection to cutting a full release, can you just double-check that this alpha release resolves all your issues?

**Comment by jeaye** [comment]
Part of the reason that we take this `:reload-all` approach is due to clojure.spec. Since we have specs for the vast majority of our functions and data, and changing some code may invalidate previous specs, or add new specs, having a single `restart!` function in a `my-proj.dev` namespace, which does a `:reload-all` and then re-instruments the code with the new specs (using [orchestra](https://github.com/jeaye/orchestra)) means that we're always running with up-to-date instrumentation for our specs. I appreciate you taking the time to do this.

With all of that said, I have verified that `0.2.2` has the issue and `0.2.3-alpha1` does not. :)

**Comment by jeaye** [comment]
@ztellman What's the verdict on this?

**Comment by ztellman** [comment]
Sorry, I keep getting side-tracked.  I'll cut the release now.

**Comment by ztellman** [comment]
`0.2.3` is available, sorry for the delay.

**Comment by jeaye** [comment]
Thank you!

**Pull request merged**
